/* CSCI 200: Assignment 2: A2 - PPM Image Editor
 *
 * Author: Dr. Jeffrey Paone
 *
 * Starting template to read a PPM file and alter the image.
 * 
 * DO NOT EDIT THIS FILE
 */

#include "ppm_functions.h"
#include <fstream>
#include <iostream>
using namespace std;

int main() {
    // prompt the user to select which PPM file to open
    const int MAX_FILE_CHOICES = print_file_options();
    const int FILE_TO_OPEN = get_user_input(MAX_FILE_CHOICES);

    // prompt the user to select which image processing technique to perform
    const int MAX_OPERATION_CHOICES = print_operation_options();
    const int OPERATION_TO_PERFORM = get_user_input(MAX_OPERATION_CHOICES);

    // open the associated input PPM and output PPM
    ifstream ppmIn;
    ofstream ppmOut;
    if( !open_files(ppmIn, ppmOut, FILE_TO_OPEN, OPERATION_TO_PERFORM) ) {
        cerr << "Error opening files" << endl;
        return -1;
    }
    
    // read image information from input PPM
    int width = 0, height = 0, maxValue = 0;
    if( !read_header_information(ppmIn, width, height, maxValue) ) {
        cerr << "Invalid PPM type" << endl;
        return -2;
    }

    // write image information to output PPM
    write_header_information(ppmOut, width, height, maxValue);

    // perform image processing technique
    read_and_write_modified_pixels(ppmIn, ppmOut, OPERATION_TO_PERFORM, width, height, maxValue);

    // close & release both the input and output PPMs
    ppmIn.close();
    ppmOut.close();

    // exit successfully
    return 0;
}